import { slugify } from "./slugify";

/**
 * Canonical URL slug for category names. Shared by client UI and server routes (counts, links).
 * Legacy slugs remain valid via directory + categoryLegacyMap.
 */
export function categoryToSlug(
  name: string,
  type: "task" | "service" | "product_sell" | "product_buy",
): string {
  const mapByType: Record<
    "task" | "service" | "product_sell" | "product_buy",
    Record<string, string>
  > = {
    task: {
      уборка: "zadachi-uborka",
      сантехника: "zadachi-santehnika",
      электрика: "zadachi-elektrika",
      "собрать мебель": "zadachi-sobrat-mebel",
      "мелкий ремонт": "zadachi-melkiy-remont",
      курьер: "zadachi-kurer",
      доставка: "zadachi-dostavka",
      грузчики: "zadachi-gruzchiki",
      переезд: "zadachi-pereezd",
      "вывезти мусор": "zadachi-vyvezti-musor",
      "настроить ПК": "zadachi-nastroit-pk",
      "починить технику": "zadachi-pochinit-tehniku",
      "помощь с телефоном": "zadachi-pomosh-s-telefonom",
      "интернет и настройка": "zadachi-internet-i-nastroyka",
      вакансии: "zadachi-vakansii",
      подработка: "zadachi-podrabotka",
      "найти помощника": "zadachi-nayti-pomoshchnika",
      разнорабочий: "zadachi-raznorabochiy",
      "поиск исполнителя": "zadachi-poisk-ispolnitelya",
      "помощь на мероприятиях": "zadachi-pomosh-na-meropriyatiyah",
      "найти жильё": "zadachi-nayti-zhilyo",
      "найти гараж": "zadachi-nayti-garazh",
      "найти авто": "zadachi-nayti-avto",
      "поиск аренды": "zadachi-poisk-arendy",
      // legacy task leaf titles (stable slugs → canonical)
      "сборка мебели": "zadachi-sobrat-mebel",
      "настройка ПК": "zadachi-nastroit-pk",
      "ремонт техники": "zadachi-pochinit-tehniku",
      "подработка и работа": "zadachi-podrabotka",
      "разовые поручения": "zadachi-raznorabochiy",
      "помощь по дому": "zadachi-melkiy-remont",
      Доставка: "zadachi-dostavka",
      "Курьерские поручения": "zadachi-kurer",
      "Компьютерная помощь": "zadachi-nastroit-pk",
      "Нужен мастер": "zadachi-poisk-ispolnitelya",
      "Ремонт техники": "zadachi-pochinit-tehniku",
      Перевозки: "zadachi-pereezd",
      "Помощь по дому": "zadachi-melkiy-remont",
      Уборка: "zadachi-uborka",
      "Разовые задания": "zadachi-raznorabochiy",
      "Срочно сегодня": "zadachi-raznorabochiy",
      "Удалённые задачи": "zadachi-raznorabochiy",
      "Организация мероприятий": "zadachi-pomosh-na-meropriyatiyah",
      "Фото и видео задачи": "zadachi-drugoe",
      "Подработка и смены": "zadachi-podrabotka",
      "Мероприятия и организация": "zadachi-pomosh-na-meropriyatiyah",
      "Офис и документы": "zadachi-drugoe",
      "Помощь с авто": "zadachi-nayti-avto",
    },
    service: {
      "ремонт квартир": "uslugi-remont-kvartir",
      строительство: "uslugi-stroitelstvo",
      сантехника: "uslugi-santehnika",
      электрика: "uslugi-elektrika",
      отделка: "uslugi-otdelka",
      "ремонт техники": "uslugi-remont-tehniki",
      компьютеры: "uslugi-kompyutery",
      сайты: "uslugi-sayty",
      настройка: "uslugi-nastroyka",
      видеонаблюдение: "uslugi-videonablyudenie",
      парикмахер: "uslugi-parikmacher",
      маникюр: "uslugi-manikyur",
      массаж: "uslugi-massazh",
      косметология: "uslugi-kosmetologiya",
      уборка: "uslugi-uborka",
      няни: "uslugi-nyani",
      сиделки: "uslugi-sidelki",
      "помощь по дому": "uslugi-pomosh-po-domu",
      эвакуатор: "uslugi-evakuator",
      грузоперевозки: "uslugi-gruzoperevozki",
      доставка: "uslugi-dostavka",
      автосервис: "uslugi-avtoservis",
      репетиторы: "uslugi-repetitory",
      фото: "uslugi-foto",
      видео: "uslugi-video",
      дизайн: "uslugi-dizayn",
      бухгалтерия: "uslugi-buhgalteriya",
      юрист: "uslugi-yurist",
      реклама: "uslugi-reklama",
      маркетинг: "uslugi-marketing",
      "аренда жилья": "uslugi-arenda-zhilya",
      риелтор: "uslugi-rieltor",
      "коммерческая недвижимость": "uslugi-kommercheskaya-nedvizhimost",
      "аренда гаражей": "uslugi-arenda-garazhey",
      // legacy service leaf titles
      юруслуги: "uslugi-yurist",
      "аренда недвижимости": "uslugi-arenda-zhilya",
      "сдаю жильё": "uslugi-arenda-zhilya",
      "коммерческая аренда": "uslugi-kommercheskaya-nedvizhimost",
      "бизнес-услуги": "uslugi-marketing",
      прокат: "uslugi-drugoe",
      автоуслуги: "uslugi-avtoservis",
      "Ремонт и строительство": "remont-i-stroitelstvo",
      "Компьютеры и техника": "uslugi-kompyutery",
      Уборка: "uslugi-uborka",
      "Перевозки и доставка": "uslugi-dostavka",
      "Красота и здоровье": "krasota-i-zdorove",
      Обучение: "uslugi-repetitory",
      "Авто услуги": "uslugi-avtoservis",
      "Риелторы и жильё": "uslugi-rieltor",
      "Юридические услуги": "uslugi-yurist",
      "Фото и видео": "uslugi-foto",
      Бухгалтерия: "uslugi-buhgalteriya",
      "Реклама и дизайн": "uslugi-dizayn",
      "Ремонт бытовой техники": "uslugi-remont-tehniki",
      Репетиторы: "uslugi-repetitory",
      Автоуслуги: "uslugi-avtoservis",
    },
    product_sell: {
      телефоны: "tovary-telefony",
      компьютеры: "tovary-kompyutery",
      ноутбуки: "tovary-noutbuki",
      техника: "tovary-tehnika",
      мебель: "tovary-mebel",
      "товары для дома": "tovary-tovary-dlya-doma",
      инструменты: "tovary-instrumenty",
      одежда: "tovary-odezhda",
      обувь: "tovary-obuv",
      сумки: "tovary-sumki",
      украшения: "tovary-ukrasheniya",
      игрушки: "tovary-igrushki",
      коляски: "tovary-kolyaski",
      "детская одежда": "tovary-detskaya-odezhda",
      автомобили: "tovary-avtomobili",
      мото: "tovary-moto",
      велосипеды: "tovary-velosipedy",
      спецтехника: "tovary-spetstehnika",
      запчасти: "tovary-zapchasti",
      шины: "tovary-shiny",
      диски: "tovary-diski",
      аккумуляторы: "tovary-akkumulyatory",
      квартиры: "tovary-kvartiry",
      дома: "tovary-doma",
      участки: "tovary-uchastki",
      гаражи: "tovary-garazhi",
      оборудование: "tovary-oborudovanie",
      станки: "tovary-stanki",
      "товары для бизнеса": "tovary-tovary-dlya-biznesa",
      спорт: "tovary-sport",
      книги: "tovary-knigi",
      музыка: "tovary-muzika",
      туризм: "tovary-turizm",
      кошки: "tovary-koshki",
      собаки: "tovary-sobaki",
      птицы: "tovary-ptitsy",
      грызуны: "tovary-gryzuny",
      рептилии: "tovary-reptilii",
      аквариумистика: "tovary-akvariumistika",
      "товары для животных": "tovary-tovary-dlya-zhivotnyh",
      // legacy product leaf titles
      "детские товары": "tovary-detskaya-odezhda",
      коммерческая: "tovary-kvartiry",
      животные: "tovary-tovary-dlya-zhivotnyh",
      отдых: "tovary-turizm",
      "Телефоны и гаджеты": "tovary-telefony",
      "Бытовая техника": "tovary-tehnika",
      "Мебель и дом": "tovary-mebel",
      "Одежда и обувь": "tovary-odezhda",
      Авто: "tovary-avtomobili",
      Животные: "tovary-tovary-dlya-zhivotnyh",
      Бесплатно: "tovary-drugoe",
      "Квартиры и дома": "tovary-kvartiry",
      "Спорт и отдых": "tovary-sport",
      "Детские товары": "tovary-detskaya-odezhda",
      "Автозапчасти и шины": "tovary-shiny",
      Электроника: "tovary-tehnika",
      "Ноутбуки и компьютеры": "tovary-noutbuki",
      Комплектующие: "tovary-zapchasti",
      Автотовары: "tovary-zapchasti",
      Запчасти: "tovary-zapchasti",
      "Шины и диски": "tovary-shiny",
      Инструменты: "tovary-instrumenty",
    },
    product_buy: {
      телефоны: "tovary-telefony",
      компьютеры: "tovary-kompyutery",
      ноутбуки: "tovary-noutbuki",
      техника: "tovary-tehnika",
      мебель: "tovary-mebel",
      "товары для дома": "tovary-tovary-dlya-doma",
      инструменты: "tovary-instrumenty",
      одежда: "tovary-odezhda",
      обувь: "tovary-obuv",
      сумки: "tovary-sumki",
      украшения: "tovary-ukrasheniya",
      игрушки: "tovary-igrushki",
      коляски: "tovary-kolyaski",
      "детская одежда": "tovary-detskaya-odezhda",
      автомобили: "tovary-avtomobili",
      мото: "tovary-moto",
      велосипеды: "tovary-velosipedy",
      спецтехника: "tovary-spetstehnika",
      запчасти: "tovary-zapchasti",
      шины: "tovary-shiny",
      диски: "tovary-diski",
      аккумуляторы: "tovary-akkumulyatory",
      квартиры: "tovary-kvartiry",
      дома: "tovary-doma",
      участки: "tovary-uchastki",
      гаражи: "tovary-garazhi",
      оборудование: "tovary-oborudovanie",
      станки: "tovary-stanki",
      "товары для бизнеса": "tovary-tovary-dlya-biznesa",
      спорт: "tovary-sport",
      книги: "tovary-knigi",
      музыка: "tovary-muzika",
      туризм: "tovary-turizm",
      кошки: "tovary-koshki",
      собаки: "tovary-sobaki",
      птицы: "tovary-ptitsy",
      грызуны: "tovary-gryzuny",
      рептилии: "tovary-reptilii",
      аквариумистика: "tovary-akvariumistika",
      "товары для животных": "tovary-tovary-dlya-zhivotnyh",
      "детские товары": "tovary-detskaya-odezhda",
      коммерческая: "tovary-kvartiry",
      животные: "tovary-tovary-dlya-zhivotnyh",
      отдых: "tovary-turizm",
      "Телефоны и гаджеты": "tovary-telefony",
      "Бытовая техника": "tovary-tehnika",
      "Мебель и дом": "tovary-mebel",
      "Одежда и обувь": "tovary-odezhda",
      Авто: "tovary-avtomobili",
      Животные: "tovary-tovary-dlya-zhivotnyh",
      Бесплатно: "tovary-drugoe",
      "Квартиры и дома": "tovary-kvartiry",
      "Спорт и отдых": "tovary-sport",
      "Детские товары": "tovary-detskaya-odezhda",
      "Автозапчасти и шины": "tovary-shiny",
      Электроника: "tovary-tehnika",
      "Ноутбуки и компьютеры": "tovary-noutbuki",
      Комплектующие: "tovary-zapchasti",
      Автотовары: "tovary-zapchasti",
      Запчасти: "tovary-zapchasti",
      "Шины и диски": "tovary-shiny",
      Инструменты: "tovary-instrumenty",
    },
  };

  if (name === "Другое") {
    if (type === "task") return "zadachi-drugoe";
    if (type === "service") return "uslugi-drugoe";
    return "tovary-drugoe";
  }

  const explicit = mapByType[type]?.[name];
  if (explicit) return explicit;
  const prefix = type === "task" ? "zadachi" : type === "service" ? "uslugi" : "tovary";
  return `${prefix}-${slugify(name)}`;
}

/** Broad homepage / parent browse slugs (not leaf subcategories). */
export function parentCategoryToSlug(
  name: string,
  type: "task" | "service" | "product_sell" | "product_buy",
): string {
  const mapByType: Record<
    "task" | "service" | "product_sell" | "product_buy",
    Record<string, string>
  > = {
    task: {
      "Дом и ремонт": "zadachi-dom-i-remont",
      "Доставка и перевозки": "zadachi-dostavka-i-perevozki",
      "Техника и IT": "zadachi-tehnika-i-it",
      "Работа и помощь": "zadachi-rabota-i-pomosh",
      Аренда: "zadachi-arenda",
      Другое: "zadachi-drugoe",
      // legacy parent titles
      "Перевозки и доставка": "zadachi-dostavka-i-perevozki",
      "Компьютеры и техника": "zadachi-tehnika-i-it",
      "Аренда и поиск": "zadachi-arenda",
    },
    service: {
      "Ремонт и строительство": "uslugi-remont-i-stroitelstvo",
      "IT и техника": "uslugi-it-i-tehnika",
      "Красота и здоровье": "uslugi-krasota-i-zdorove",
      "Дом и быт": "uslugi-dom-i-byt",
      "Автоуслуги и перевозки": "uslugi-avtouslugi-i-perevozki",
      "Обучение и медиа": "uslugi-obuchenie-i-media",
      "Бизнес и документы": "uslugi-biznes-i-dokumenty",
      Недвижимость: "uslugi-nedvizhimost",
      Другое: "uslugi-drugoe",
      // legacy parent titles
      "Перевозки и авто": "uslugi-avtouslugi-i-perevozki",
      "Бизнес и аренда": "uslugi-biznes-i-dokumenty",
      "Недвижимость и аренда": "uslugi-nedvizhimost",
    },
    product_sell: {
      Электроника: "tovary-elektronika",
      "Дом и мебель": "tovary-dom-i-mebel",
      "Одежда и аксессуары": "tovary-odezhda-i-aksessuary",
      "Детские товары": "tovary-detskie-tovary",
      "Авто и транспорт": "tovary-avto-i-transport",
      "Запчасти и аксессуары": "tovary-zapchasti-i-aksessuary",
      Недвижимость: "tovary-nedvizhimost",
      "Бизнес и оборудование": "tovary-biznes-i-oborudovanie",
      "Хобби и отдых": "tovary-hobbi-i-otdyh",
      Животные: "tovary-zhivotnye",
      Другое: "tovary-drugoe",
      // legacy parent titles
      "Одежда и дети": "tovary-odezhda-i-aksessuary",
      "Авто и запчасти": "tovary-avto-i-transport",
      "Хобби и животные": "tovary-hobbi-i-otdyh",
    },
    product_buy: {
      Электроника: "tovary-elektronika",
      "Дом и мебель": "tovary-dom-i-mebel",
      "Одежда и аксессуары": "tovary-odezhda-i-aksessuary",
      "Детские товары": "tovary-detskie-tovary",
      "Авто и транспорт": "tovary-avto-i-transport",
      "Запчасти и аксессуары": "tovary-zapchasti-i-aksessuary",
      Недвижимость: "tovary-nedvizhimost",
      "Бизнес и оборудование": "tovary-biznes-i-oborudovanie",
      "Хобби и отдых": "tovary-hobbi-i-otdyh",
      Животные: "tovary-zhivotnye",
      Другое: "tovary-drugoe",
      "Одежда и дети": "tovary-odezhda-i-aksessuary",
      "Авто и запчасти": "tovary-avto-i-transport",
      "Хобби и животные": "tovary-hobbi-i-otdyh",
    },
  };

  if (name === "Другое") {
    if (type === "task") return "zadachi-drugoe";
    if (type === "service") return "uslugi-drugoe";
    return "tovary-drugoe";
  }

  const explicit = mapByType[type]?.[name];
  if (explicit) return explicit;
  const prefix = type === "task" ? "zadachi" : type === "service" ? "uslugi" : "tovary";
  return `${prefix}-gruppa-${slugify(name)}`;
}
